[project]
name = "19-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,sql-database]>=1.19.1",
    "ipykernel>=7.1.0",
]
